# -*- coding: utf-8 -*-
"""LVADSUSR67_Aishwarya_lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U660vcVNSC-vl4eo0Qo1ntvFFZfj-zdh
"""

import pandas as pd
import numpy as np

data=pd.read_csv('/content/expenses.csv')
df=pd.DataFrame(data)
df

#Info of the dataframe
df.info()

df.describe()

#1.5
#1
#Checking for null values
df.isnull().sum()

df.duplicated().sum()

#1.5
#1
#Dropping duplicate values
df.drop_duplicates()

#1.5
#1
#Checking outliers
sns.boxplot(df['age'])

#As there are no outliers we need not address this column

#1.5
#1
#Finding Correlation
df.corr()

#1.5
#2
#Encoding Categorical Values
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['smoker']=le.fit_transform(df['smoker'])
df['sex']=le.fit_transform(df['sex'])
df['region']=le.fit_transform(df['region'])

df

#1.5
#3
#Analyzing Data
sns.heatmap(df.corr(),annot=True)

df.isnull().sum()

df.duplicated().sum()

sns.regplot(x=df['age'],y=df['charges'])

#1.5
#3
#Spliiting Data
x=df[['age','sex','bmi','children','smoker','region']]
y=df['charges']
x

#1.5
#4,5
#Splitting Data into training and testing data and performing Linear Regression
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.3,random_state=420)
train_x=sc.fit_transform(train_x)
test_x=sc.fit_transform(test_x)
lr.fit(train_x,train_y)
pred=lr.predict(test_x)

#1.5
#6
#Mean Square Error and RMSE
from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(test_y, pred)
print("Mean Squared Error:",mse)
srt=np.sqrt(mse)
print("Root mean square error:",srt)

#1.5
#6
#R-Squared
r2 = r2_score(test_y,pred)
print(r2)